# Generated by Django 5.1.5 on 2026-10-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
