# Generated by Django 5.1.5 on 2026-10-01 09:47

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('freeze_start_date', models.DateField()),
                ('freeze_end_date', models.DateField(blank=True, null=True)),
                ('days_added', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freezes_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.gym')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to='memberships.membership')),
            ],
            options={
                'ordering': ['-freeze_start_date'],
                'indexes': [models.Index(fields=['gym', 'membership'], name='memberships_gym_id_572b06_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
