# Generated by Django 5.1.5 on 2026-10-01 09:23

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_member_managers'),
        ('memberships', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='tenants.gym')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('gym', 'year'), name='uniq_invoice_seq_gym_year')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('enrollment', 'Enrollment'), ('renewal', 'Renewal'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], default='enrollment', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank transfer'), ('other', 'Other')], default='cash', max_length=10)),
                ('amount_paise', models.IntegerField()),
                ('discount_paise', models.PositiveIntegerField(default=0)),
                ('invoice_number', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_amount_paise', models.IntegerField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenants.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.gym')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='memberships.membership')),
                ('refund_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', '-created_at'], name='payments_pa_gym_id_a104e8_idx'), models.Index(fields=['gym', 'member'], name='payments_pa_gym_id_8e84db_idx')],
                'constraints': [models.UniqueConstraint(fields=('gym', 'invoice_number'), name='uniq_payment_invoice_per_gym'), models.CheckConstraint(condition=models.Q(('amount_paise', 0), _negated=True), name='payment_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('amount_paise__lt', 0), ('kind', 'refund')), models.Q(models.Q(('kind', 'refund'), _negated=True), ('amount_paise__gt', 0)), _connector='OR'), name='payment_sign_matches_kind'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'refund'), ('refund_of__isnull', False)), models.Q(models.Q(('kind', 'refund'), _negated=True), ('refund_of__isnull', True)), _connector='OR'), name='refund_requires_link')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
