# Generated by Django 5.1.5 on 2026-10-01 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('enroll', 'Enroll'), ('renew', 'Renew'), ('refund', 'Refund'), ('edit_payment', 'Edit payment'), ('correct', 'Correct membership'), ('cancel', 'Cancel membership')], max_length=20)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=40)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.branch')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.gym')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['gym', '-created_at'], name='audit_audit_gym_id_8bf289_idx'), models.Index(fields=['gym', 'entity_type', 'entity_id'], name='audit_audit_gym_id_8ee8e1_idx')],
            },
        ),
    ]
